[package]
name = "private-box"
description = "A direct port of https://github.com/auditdrivencrypto/private-box"
version = "0.3.0"
authors = ["Piet Geursen <pietgeursen@gmail.com>"]
license = "MIT"

[dependencies]
libsodium-sys = "0.0.16"
sodiumoxide = "0.0.16"
arrayref = "0.3.4"
serde = "1.0.27"
serde_json = "1.0"
serde_derive = "1.0.27"
base64 = "0.9"

